spring:
  application:
    name: backend

  config:
    import: "classpath:./config/local-var.yml"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${database.url}"
    username: "${database.username}"
    password: "${database.password}"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: "${jwt.hashcode}"

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: "${oauth2.naver.id}"
            client-secret: "${oauth2.naver.secret}"
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: "${oauth2.google.id}"
            client-secret: "${oauth2.google.secret}"
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          kakao:
            client-name: kakao
            client-id: "${oauth2.kakao.id}"
            client-secret: "${oauth2.kakao.secret}"
            redirect:uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id